# Generated by Django 3.2.13 on 2022-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scane', '0003_alter_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNASeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PeptideSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RNASeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=2000)),
            ],
        ),
    ]
